package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Generator'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Generator")) {
    expectSteps {
        script {
            name = "Generate dsl params file"
            id = "Generate_Dsl_Params"
            scriptContent = """
                #!/usr/bin/env bash
                set -euo pipefail
                
                cd .teamcity
                touch params.properties
                
                echo "IS_DYNAMIC_CHAIN=true" > params.properties
            """.trimIndent()
        }
        script {
            name = "Generate Settings"
            scriptContent = """
                cd .teamcity/
                
                curl -sSf -u "%agent_username%:%agent_password%" -o dsl-context.zip "%DSL_CONTEXT_URL%"
                
                JAVA_HOME=~/.asdf/installs/java/corretto-21.0.11.10.1 mvn -Dteamcity.versionedSettings.exposeInternalParameters=true -Dteamcity.internal.dsl.IS_DYNAMIC_CHAIN=true -DserverContext=dsl-context.zip teamcity-configs:generate -f pom.xml
                
                rm -rf "target/generated-configs/%DSL_RELATIVE_ROOT_ID%"
            """.trimIndent()
        }
    }
    steps {
        insert(2) {
            step {
                id = "jetbrains_dynamic_build_chain_settings_generator_1_0_0"
                type = "jetbrains/dynamic-build-chain-settings-generator@1.0.0"
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("agent_username", "credentialsJSON:3ef89e54-c228-485b-9fcc-d2c5c27df087")
                param("plugin.docker.imagePlatform", "")
                param("agent_password", "credentialsJSON:3ef89e54-c228-485b-9fcc-d2c5c27df087")
                param("plugin.docker.imageId", "")
                param("teamcity.step.phase", "")
                param("SERVER_URL", "%teamcity.serverUrl%")
                param("plugin.docker.run.parameters", "")
                param("PROJECT_ID", "DynamicBuildChains")
            }
        }
    }
}
