package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildStep
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Generator'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Generator")) {
    expectSteps {
        step {
            id = "jetbrains_dynamic_build_chain_settings_generator_1_0_0"
            type = "jetbrains/dynamic-build-chain-settings-generator@1.0.0"
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("SERVER_URL", "%teamcity.serverUrl%")
            param("env.input_params", "param1=value,param2=value2")
            param("agent_token", "credentialsJSON:faf07e91-2bfe-479f-b51c-ab2dff63dd10")
            param("PROJECT_ID", "DynamicBuildChains")
        }
    }
    steps {
        update<BuildStep>(0) {
            id = "jetbrains_dynamic_build_chain_settings_generator_1_0_0"
            clearConditions()
            param("agent_token", "credentialsJSON:1eae8804-2e9c-47e0-85ee-f7471d1d4ddb")
            param("plugin.docker.imagePlatform", "")
            param("plugin.docker.imageId", "")
            param("teamcity.step.phase", "")
            param("plugin.docker.run.parameters", "")
            param("PROJECT_ID", "")
        }
    }
}
